# -*- coding: utf-8 -*-
"""분석 및 자동화.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S0xT-Mj9LpgTyUvds5imgtShWqHrSnGl
"""

! pip uninstall -y google-generativeai
! pip install google-genai python-docx

import os
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from google import genai
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

# 💡 여기에 본인의 유효한 Gemini API 키를 입력하세요.
GEMINI_API_KEY = "GEMINI_API_KEY"

client = genai.Client(api_key=GEMINI_API_KEY)

def run_ml_and_extract_assets(data_path="cvd_process_data.csv", output_dir="report_assets"):
    """[1단계] 머신러닝 분석 실행 및 결과/그래프 추출 (구간별 비교 그래프 포함)"""
    print("--- [1/3단계] 머신러닝 분석 및 에셋 추출 시작 ---")
    os.makedirs(output_dir, exist_ok=True)
    df = pd.read_csv(data_path)

    features = ['Temperature_C', 'Pressure_Torr', 'Gas_Flow_sccm', 'RF_Power_W', 'Depo_Time_sec']
    X = df[features]
    y = df['Thickness_nm']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # 1. 전체 데이터 학습 및 중요도
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    importances = model.feature_importances_
    top_feature_total = features[np.argmax(importances)]

    # 2. 저온 구간 학습 및 중요도 추출
    df_low = df[df['Temperature_C'] <= 420]
    rf_low = RandomForestRegressor(n_estimators=50, random_state=42)
    rf_low.fit(df_low[features], df_low['Thickness_nm'])
    importances_low = rf_low.feature_importances_
    top_feature_low = features[np.argmax(importances_low)]

    # 3. 고온 구간 학습 및 중요도 추출
    df_high = df[df['Temperature_C'] > 420]
    rf_high = RandomForestRegressor(n_estimators=50, random_state=42)
    rf_high.fit(df_high[features], df_high['Thickness_nm'])
    importances_high = rf_high.feature_importances_
    top_feature_high = features[np.argmax(importances_high)]

    real_results = {
        "mse": round(mse, 4),
        "r2": round(r2, 2),
        "top_feature_total": top_feature_total,
        "top_feature_low": top_feature_low,
        "top_feature_high": top_feature_high
    }

    # --- [그래프 1] 실제값 vs 예측값 산점도 ---
    plt.figure(figsize=(6, 5))
    plt.scatter(y_test, y_pred, color='blue', alpha=0.6, edgecolors='k')
    plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
    plt.title('Actual vs Predicted Thickness')
    plt.savefig(os.path.join(output_dir, '1_actual_vs_predicted.png'), dpi=300)
    plt.close()

    # --- [그래프 2] 전체 변수 중요도 바차트 ---
    plt.figure(figsize=(6, 5))
    indices = np.argsort(importances)[::-1]
    plt.bar(range(X.shape[1]), importances[indices], color='teal', edgecolor='k')
    plt.xticks(range(X.shape[1]), [features[i] for i in indices], rotation=25)
    plt.title('Overall Feature Importances')
    plt.savefig(os.path.join(output_dir, '2_feature_importances.png'), dpi=300)
    plt.close()

    # --- [그래프 3] 저온/고온 구간별 중요도 비교 그룹 바차트 (요청하신 형태 반영) ---
    plt.figure(figsize=(8, 5))
    x = np.arange(len(features))
    width = 0.35

    labels_clean = ['Temp', 'Pressure', 'Gas Flow', 'RF Power', 'Depo Time']

    plt.bar(x - width/2, importances_low, width, label='Low Temp Regime (≤420°C)', color='#d9534f', edgecolor='k')
    plt.bar(x + width/2, importances_high, width, label='High Temp Regime (>420°C)', color='#428bca', edgecolor='k')

    plt.axhline(0, color='grey', linewidth=0.8)
    plt.grid(axis='y', linestyle='-', alpha=0.7)
    plt.title('Feature Importance Shift by Temperature Regime')
    plt.ylabel('Importance Score')
    plt.xticks(x, labels_clean)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, '3_regime_comparison.png'), dpi=300)
    plt.close()

    print("✅ 실제 ML 결과 및 구간별 비교 그래프 추출 완료!")
    return real_results

def generate_dynamic_analysis_text(results):
    """[2단계] 서버 과부하 대응 재시도 로직 포함 AI 텍스트 생성"""
    print("--- [2/3단계] AI 동적 텍스트 생성 시작 ---")

    prompt = f"""
    너는 반도체 CVD 공정 데이터를 철저하게 교차 검증하고 논리적 근거를 바탕으로 분석하는 화학공학 엔지니어 봇이야.
    아래 제공된 실제 머신러닝 분석 결과를 바탕으로, '보고서에 들어갈 3개의 문단'을 작성해 줘.

    [실제 분석 결과 데이터]
    - R² Score: {results['r2']}
    - MSE: {results['mse']}
    - 전체 데이터 1위 제어 변수: {results['top_feature_total']}
    - 저온(≤420℃) 구간 1위 제어 변수: {results['top_feature_low']}
    - 고온(>420℃) 구간 1위 제어 변수: {results['top_feature_high']}

    [출력 형식]
    반드시 아래의 구분자([섹션1], [섹션2], [섹션3])를 포함하여 작성할 것.
    [섹션1] (모델의 예측 성능에 대한 요약)
    [섹션2] (전체 데이터 1위 변수에 대한 화학공학적 속도론 해석)
    [섹션3] (온도 구간별 1위 변수가 달라진 메커니즘 전이 현상 해석)
    """

    max_retries = 3
    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model='gemini-3.6-flash',
                contents=prompt,
            )
            text = response.text

            sec1 = text.split('[섹션1]')[1].split('[섹션2]')[0].strip()
            sec2 = text.split('[섹션2]')[1].split('[섹션3]')[0].strip()
            sec3 = text.split('[섹션3]')[1].strip()
            print("✅ AI 텍스트 초안 생성 완료!")
            return sec1, sec2, sec3

        except Exception as e:
            print(f"⚠️ [시도 {attempt+1}/{max_retries}] API 호출 지연/실패: {e}")
            if attempt < max_retries - 1:
                print("⏳ 3초 후 서버에 재연결을 시도합니다...")
                time.sleep(3)
            else:
                print("💡 모든 재시도 실패. 비상용 동적 템플릿(플랜 B)을 가동합니다.")

    sec1_fallback = f"학습된 랜덤 포레스트 모델을 테스트 데이터에 적용해 본 결과, 결정계수 R² ≒ {results['r2']} (MSE: {results['mse']}) 수준의 예측 정확도를 보였습니다."
    sec2_fallback = f"전체 데이터 기준 변수 중요도 분석 결과, '{results['top_feature_total']}' 변수가 가장 높은 기여도를 보였습니다."
    sec3_fallback = f"저온 구간에서는 '{results['top_feature_low']}' 변수가, 고온 구간에서는 '{results['top_feature_high']}' 변수가 1위 제어 변수로 나타나는 메커니즘 전이 현상이 확인되었습니다."
    return sec1_fallback, sec2_fallback, sec3_fallback

def build_word_report(sec_texts, asset_dir="report_assets", output_filename="Final_CVD_Report.docx"):
    """[3단계] 워드 문서 구조 조립 및 모든 그래프 삽입"""
    print("--- [3/3단계] Word 보고서 조립 시작 ---")
    doc = Document()

    style = doc.styles['Normal']
    font = style.font
    font.name = 'Malgun Gothic'
    font.size = Pt(10.5)

    doc.add_heading('CVD 공정 조건에 따른 무기 박막소재 데이터 분석', level=0)

    doc.add_heading('1. 서론 및 연구 목적', level=1)
    doc.add_paragraph(
        "반도체 미세공정에서 널리 쓰이는 무기 박막소재들은 전구체 가스의 화학 반응을 통해 증착됩니다. "
        "본 보고서는 머신러닝 기술을 응용해 CVD 공정 변수가 박막 소재의 두께에 미치는 영향을 "
        "데이터 기반으로 분석하고 속도론적 관점에서 해석한 결과입니다."
    )

    doc.add_heading('2. 결과 분석 및 화학공학적 관점에서의 해석', level=1)

    doc.add_heading('1) 모델 예측 성능 확인', level=2)
    doc.add_paragraph(sec_texts[0])
    if os.path.exists(os.path.join(asset_dir, '1_actual_vs_predicted.png')):
        doc.add_picture(os.path.join(asset_dir, '1_actual_vs_predicted.png'), width=Inches(5.0))

    doc.add_heading('2) 변수 중요도 분석을 통한 속도론적 해석', level=2)
    doc.add_paragraph(sec_texts[1])
    if os.path.exists(os.path.join(asset_dir, '2_feature_importances.png')):
        doc.add_picture(os.path.join(asset_dir, '2_feature_importances.png'), width=Inches(5.0))

    doc.add_heading('3) 온도 구간별 메커니즘 전이 현상', level=2)
    doc.add_paragraph(sec_texts[2])
    # 💡 요청하신 저온/고온 구간별 비교 그룹 바차트 삽입
    if os.path.exists(os.path.join(asset_dir, '3_regime_comparison.png')):
        doc.add_picture(os.path.join(asset_dir, '3_regime_comparison.png'), width=Inches(5.5))

    doc.save(output_filename)
    print(f"✅ 최종 자동화 Word 보고서 완성: {output_filename}")
    print("--- [모든 프로세스 완료] ---")

if __name__ == "__main__":
    actual_ml_results = run_ml_and_extract_assets(data_path="cvd_process_data.csv")
    ai_generated_texts = generate_dynamic_analysis_text(actual_ml_results)
    build_word_report(ai_generated_texts)